// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoV4wUzBlNc9F5-UbQu9PgwcWi-Sge4A',
    appId: '1:497439407740:web:a2f045d62a7a43829713f9',
    messagingSenderId: '497439407740',
    projectId: 'gp-e-commerce-application',
    authDomain: 'gp-e-commerce-application.firebaseapp.com',
    storageBucket: 'gp-e-commerce-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArJCjcC0l16z3FhrQ0aJ-1NcLXUxa8YXQ',
    appId: '1:497439407740:android:25f5ac613937213f9713f9',
    messagingSenderId: '497439407740',
    projectId: 'gp-e-commerce-application',
    storageBucket: 'gp-e-commerce-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG8GX1NjrpQxemoG_73ePO8QQc7x_aapc',
    appId: '1:497439407740:ios:03be63a568387b719713f9',
    messagingSenderId: '497439407740',
    projectId: 'gp-e-commerce-application',
    storageBucket: 'gp-e-commerce-application.appspot.com',
    iosClientId: '497439407740-qsfnt99349aesmio6lcobehoqkgalrh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG8GX1NjrpQxemoG_73ePO8QQc7x_aapc',
    appId: '1:497439407740:ios:03be63a568387b719713f9',
    messagingSenderId: '497439407740',
    projectId: 'gp-e-commerce-application',
    storageBucket: 'gp-e-commerce-application.appspot.com',
    iosClientId: '497439407740-qsfnt99349aesmio6lcobehoqkgalrh1.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
}
